from typing import Any

class Settings:
    def __init__(self, **kwargs: Any) -> None: ...

class Artifact:
    aliases: list[str]
    metadata: dict[str, Any]
    def __init__(self, name: str, type: str, **kwargs: Any) -> None: ...
    def add_dir(self, local_path: str, **kwargs: Any) -> None: ...
    def add_file(self, local_path: str, **kwargs: Any) -> None: ...
    def download(self, **kwargs: Any) -> str: ...
    def save(self) -> None: ...
    def wait(self) -> Artifact: ...

class Run:
    entity: str
    project: str
    name: str
    config: Any
    _is_finished: bool
    def finish(self, *args: Any, **kwargs: Any) -> None: ...
    def define_metric(self, *args: Any, **kwargs: Any) -> None: ...
    def log(self, *args: Any, **kwargs: Any) -> None: ...
    def log_artifact(self, *args: Any, **kwargs: Any) -> Artifact: ...

class Api:
    default_entity: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def artifact(self, *args: Any, **kwargs: Any) -> Artifact: ...
    def artifacts(self, *args: Any, **kwargs: Any) -> list[Artifact]: ...
    def run(self, *args: Any, **kwargs: Any) -> Run: ...

def init(*args: Any, **kwargs: Any) -> Run: ...
def login(*args: Any, **kwargs: Any) -> Any: ...

class errors:
    class CommError(Exception): ...
