"""DeepSeek-V4 context-parallel attention support."""

from .compressor import (
    build_dsv4_compressed_layout,
    build_dsv4_compressed_layout_from_cp_state,
    compress_owned_projected_kv,
    compress_projected_kv,
)
from .cp_attention import (
    compute_single_sink_grad,
    merge_single_sink_branch,
    merge_stage_outputs,
    merge_two_stage_outputs,
)
from .cp_stage import (
    build_dsv4_stage_inputs,
    build_stage_local_topk_for_csa,
    build_stage_local_topk_for_hca,
    raw_swa_token_ids_for_query,
)
from .indexer import (
    build_indexer_visibility_mask,
    compute_indexer_scores,
    compute_indexer_topk,
    merge_indexer_topk_results,
    stable_topk_by_score_and_id,
    stage_candidate_entry_ids,
    visible_entry_ids_for_query,
)
from .types import (
    Dsv4BranchView,
    Dsv4CompressedEntry,
    Dsv4CompressedLayout,
    Dsv4CompressionKind,
    Dsv4CompressionSpec,
    Dsv4ContextParallelState,
    Dsv4HaloTransfer,
    Dsv4PreparedPlan,
    Dsv4StageInputs,
    Dsv4StageKeyKind,
    Dsv4StreamKind,
    Dsv4StreamSpec,
    Dsv4TokenInView,
    Dsv4TopkResult,
)

__all__ = [
    "Dsv4BranchView",
    "Dsv4CompressedEntry",
    "Dsv4CompressedLayout",
    "Dsv4CompressionKind",
    "Dsv4CompressionSpec",
    "Dsv4ContextParallelState",
    "Dsv4HaloTransfer",
    "Dsv4PreparedPlan",
    "Dsv4StageInputs",
    "Dsv4StageKeyKind",
    "Dsv4StreamKind",
    "Dsv4StreamSpec",
    "Dsv4TokenInView",
    "Dsv4TopkResult",
    "build_dsv4_compressed_layout",
    "build_dsv4_compressed_layout_from_cp_state",
    "build_dsv4_stage_inputs",
    "build_indexer_visibility_mask",
    "build_stage_local_topk_for_csa",
    "build_stage_local_topk_for_hca",
    "compute_single_sink_grad",
    "compute_indexer_scores",
    "compute_indexer_topk",
    "compress_owned_projected_kv",
    "compress_projected_kv",
    "merge_single_sink_branch",
    "merge_indexer_topk_results",
    "merge_stage_outputs",
    "merge_two_stage_outputs",
    "raw_swa_token_ids_for_query",
    "stable_topk_by_score_and_id",
    "stage_candidate_entry_ids",
    "visible_entry_ids_for_query",
]
